version: '3'

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  person_api:
    build: person_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./person_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5001:5000"

  location_api:
    build: location_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./location_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5002:5000"

  connection_api:
    build: connection_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./connection_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5003:5000"

  client:
    tty: true
    build: frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules: